language: node_js
node_js:
- lts/*
sudo: false
after_success:
- "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: WzgwCGWuxBlA0jRrChv7tszs5jJmoRh45eSwihjRu0nVjTxadPgkYs8rkANh3py2Kp+7kAdFZaKxCiZodSJZklBwYdp0ZsDg9uQFzg6ZTWdkYAE29/lqhp49xcoPZgvvZkVeK7Z0lqXJUmqfb6NIba+udGaofIEHZm++CvHZ+is=
  on:
    tags: true
    repo: noflo/noflo-runtime-websocket
  skip_cleanup: true
